sculpin_content_types:
    posts:
        permalink: :filename/
    guias:
        layout: guias
        permalink: guias/:slug_filename/
    secciones:
        type: meta
        singular_name: seccion
        layout: seccion
