sculpin_content_types:
    posts:
        permalink: :filename/
    guias:
        layout: default
        permalink: guias/:slug_filename/
    secciones:
        layout: secciones
        singular_name: seccion
        permalink: guias/seccion/:slug_filename/
